name: Test
on: ['deployment']
jobs:
  deployment:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: deploy nnabla.org
        run: |
          echo "environment - ${{ github.event.deployment.task }}"
          echo "payload - ${{ github.event.deployment.payload }}"
          make make-test
      
      - name: Docker Hub Description
      - uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: jiaqi2020/test2020
          README_FILEPATH: ./README.md
#    - name: 'deployment pending'
#      uses: 'deliverybot/deployment-status@master'
#      with:
#        state: 'pending'
#        token: '${{ github.token }}'
#
#    - uses: actions/checkout@v2
#    - name: deploy
#      run: |
#        echo "environment - ${{ github.event.deployment.task }}"
#        echo "payload - ${{ github.event.deployment.payload }}"
#        make make-test
#
#    - name: 'deployment success'
#      if: success()
#      uses: 'deliverybot/deployment-status@master'
#      with:
#        state: 'success'
#        token: '${{ github.token }}'
#
#    - name: 'deployment failure'
#      if: failure()
#      uses: 'deliverybot/deployment-status@master'
#      with:
#        state: 'failure'
#        token: '${{ github.token }}'
